/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityCourtAndLawsRouteImport } from './routes/community-court-and-laws'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as AboutUsHeritageRouteImport } from './routes/about-us.heritage'
import { Route as AboutUsSupportStructureRouteImport } from './routes/about-us.support-structure'
import { Route as AboutUsUbukhosiBakwazondiRouteImport } from './routes/about-us.ubukhosi-bakwazondi'
import { Route as ProgramsAgricultureRouteImport } from './routes/programs.agriculture'
import { Route as ProgramsElectricityWaterRouteImport } from './routes/programs.electricity-water'
import { Route as ProgramsSafetySecurityRouteImport } from './routes/programs.safety-security'
import { Route as ProgramsSocialDevelopmentRouteImport } from './routes/programs.social-development'
import { Route as ProgramsYouthDevelopmentRouteImport } from './routes/programs.youth-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCourtAndLawsRoute = CommunityCourtAndLawsRouteImport.update({
  id: '/community-court-and-laws',
  path: '/community-court-and-laws',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsHeritageRoute = AboutUsHeritageRouteImport.update({
  id: '/about-us/heritage',
  path: '/about-us/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsSupportStructureRoute = AboutUsSupportStructureRouteImport.update({
  id: '/about-us/support-structure',
  path: '/about-us/support-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsUbukhosiBakwazondiRoute =
  AboutUsUbukhosiBakwazondiRouteImport.update({
    id: '/about-us/ubukhosi-bakwazondi',
    path: '/about-us/ubukhosi-bakwazondi',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsAgricultureRoute = ProgramsAgricultureRouteImport.update({
  id: '/programs/agriculture',
  path: '/programs/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsElectricityWaterRoute =
  ProgramsElectricityWaterRouteImport.update({
    id: '/programs/electricity-water',
    path: '/programs/electricity-water',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsSafetySecurityRoute = ProgramsSafetySecurityRouteImport.update({
  id: '/programs/safety-security',
  path: '/programs/safety-security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSocialDevelopmentRoute =
  ProgramsSocialDevelopmentRouteImport.update({
    id: '/programs/social-development',
    path: '/programs/social-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsYouthDevelopmentRoute =
  ProgramsYouthDevelopmentRouteImport.update({
    id: '/programs/youth-development',
    path: '/programs/youth-development',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-court-and-laws': typeof CommunityCourtAndLawsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/newsletter': typeof NewsletterRoute
  '/about-us/heritage': typeof AboutUsHeritageRoute
  '/about-us/support-structure': typeof AboutUsSupportStructureRoute
  '/about-us/ubukhosi-bakwazondi': typeof AboutUsUbukhosiBakwazondiRoute
  '/programs/agriculture': typeof ProgramsAgricultureRoute
  '/programs/electricity-water': typeof ProgramsElectricityWaterRoute
  '/programs/safety-security': typeof ProgramsSafetySecurityRoute
  '/programs/social-development': typeof ProgramsSocialDevelopmentRoute
  '/programs/youth-development': typeof ProgramsYouthDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-court-and-laws': typeof CommunityCourtAndLawsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/newsletter': typeof NewsletterRoute
  '/about-us/heritage': typeof AboutUsHeritageRoute
  '/about-us/support-structure': typeof AboutUsSupportStructureRoute
  '/about-us/ubukhosi-bakwazondi': typeof AboutUsUbukhosiBakwazondiRoute
  '/programs/agriculture': typeof ProgramsAgricultureRoute
  '/programs/electricity-water': typeof ProgramsElectricityWaterRoute
  '/programs/safety-security': typeof ProgramsSafetySecurityRoute
  '/programs/social-development': typeof ProgramsSocialDevelopmentRoute
  '/programs/youth-development': typeof ProgramsYouthDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-court-and-laws': typeof CommunityCourtAndLawsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/newsletter': typeof NewsletterRoute
  '/about-us/heritage': typeof AboutUsHeritageRoute
  '/about-us/support-structure': typeof AboutUsSupportStructureRoute
  '/about-us/ubukhosi-bakwazondi': typeof AboutUsUbukhosiBakwazondiRoute
  '/programs/agriculture': typeof ProgramsAgricultureRoute
  '/programs/electricity-water': typeof ProgramsElectricityWaterRoute
  '/programs/safety-security': typeof ProgramsSafetySecurityRoute
  '/programs/social-development': typeof ProgramsSocialDevelopmentRoute
  '/programs/youth-development': typeof ProgramsYouthDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-court-and-laws'
    | '/contact'
    | '/faqs'
    | '/newsletter'
    | '/about-us/heritage'
    | '/about-us/support-structure'
    | '/about-us/ubukhosi-bakwazondi'
    | '/programs/agriculture'
    | '/programs/electricity-water'
    | '/programs/safety-security'
    | '/programs/social-development'
    | '/programs/youth-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-court-and-laws'
    | '/contact'
    | '/faqs'
    | '/newsletter'
    | '/about-us/heritage'
    | '/about-us/support-structure'
    | '/about-us/ubukhosi-bakwazondi'
    | '/programs/agriculture'
    | '/programs/electricity-water'
    | '/programs/safety-security'
    | '/programs/social-development'
    | '/programs/youth-development'
  id:
    | '__root__'
    | '/'
    | '/community-court-and-laws'
    | '/contact'
    | '/faqs'
    | '/newsletter'
    | '/about-us/heritage'
    | '/about-us/support-structure'
    | '/about-us/ubukhosi-bakwazondi'
    | '/programs/agriculture'
    | '/programs/electricity-water'
    | '/programs/safety-security'
    | '/programs/social-development'
    | '/programs/youth-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityCourtAndLawsRoute: typeof CommunityCourtAndLawsRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  NewsletterRoute: typeof NewsletterRoute
  AboutUsHeritageRoute: typeof AboutUsHeritageRoute
  AboutUsSupportStructureRoute: typeof AboutUsSupportStructureRoute
  AboutUsUbukhosiBakwazondiRoute: typeof AboutUsUbukhosiBakwazondiRoute
  ProgramsAgricultureRoute: typeof ProgramsAgricultureRoute
  ProgramsElectricityWaterRoute: typeof ProgramsElectricityWaterRoute
  ProgramsSafetySecurityRoute: typeof ProgramsSafetySecurityRoute
  ProgramsSocialDevelopmentRoute: typeof ProgramsSocialDevelopmentRoute
  ProgramsYouthDevelopmentRoute: typeof ProgramsYouthDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-court-and-laws': {
      id: '/community-court-and-laws'
      path: '/community-court-and-laws'
      fullPath: '/community-court-and-laws'
      preLoaderRoute: typeof CommunityCourtAndLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/heritage': {
      id: '/about-us/heritage'
      path: '/about-us/heritage'
      fullPath: '/about-us/heritage'
      preLoaderRoute: typeof AboutUsHeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/support-structure': {
      id: '/about-us/support-structure'
      path: '/about-us/support-structure'
      fullPath: '/about-us/support-structure'
      preLoaderRoute: typeof AboutUsSupportStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/ubukhosi-bakwazondi': {
      id: '/about-us/ubukhosi-bakwazondi'
      path: '/about-us/ubukhosi-bakwazondi'
      fullPath: '/about-us/ubukhosi-bakwazondi'
      preLoaderRoute: typeof AboutUsUbukhosiBakwazondiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/agriculture': {
      id: '/programs/agriculture'
      path: '/programs/agriculture'
      fullPath: '/programs/agriculture'
      preLoaderRoute: typeof ProgramsAgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/electricity-water': {
      id: '/programs/electricity-water'
      path: '/programs/electricity-water'
      fullPath: '/programs/electricity-water'
      preLoaderRoute: typeof ProgramsElectricityWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/safety-security': {
      id: '/programs/safety-security'
      path: '/programs/safety-security'
      fullPath: '/programs/safety-security'
      preLoaderRoute: typeof ProgramsSafetySecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/social-development': {
      id: '/programs/social-development'
      path: '/programs/social-development'
      fullPath: '/programs/social-development'
      preLoaderRoute: typeof ProgramsSocialDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/youth-development': {
      id: '/programs/youth-development'
      path: '/programs/youth-development'
      fullPath: '/programs/youth-development'
      preLoaderRoute: typeof ProgramsYouthDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityCourtAndLawsRoute: CommunityCourtAndLawsRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  NewsletterRoute: NewsletterRoute,
  AboutUsHeritageRoute: AboutUsHeritageRoute,
  AboutUsSupportStructureRoute: AboutUsSupportStructureRoute,
  AboutUsUbukhosiBakwazondiRoute: AboutUsUbukhosiBakwazondiRoute,
  ProgramsAgricultureRoute: ProgramsAgricultureRoute,
  ProgramsElectricityWaterRoute: ProgramsElectricityWaterRoute,
  ProgramsSafetySecurityRoute: ProgramsSafetySecurityRoute,
  ProgramsSocialDevelopmentRoute: ProgramsSocialDevelopmentRoute,
  ProgramsYouthDevelopmentRoute: ProgramsYouthDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
